feat/connector-elsys
tago-io/decoders pull request #36
Opened 2024-06-28 14:50 UTC by mateuscardosodeveloper

## Decoder Description

Add ELSYS sensor decoders

## Type of change

- [x] Adding a new Decoder of Connector
- [ ] Adding a new Decoder of Network
- [ ] Update or fixing an issue in existing Decoder

## Decoder Information and Payload to test and review

- [ ] Documentation of the hardware or protocol:
- [ ] Payload of example the test the decoder:

## Checklist for Adding a New Decoder

- [ ] Created a new folder under `./decoders/network/` or `./decoders/connector/` with the name of your decoder.
- [ ] Added a `network.jsonc` or `connector.jsonc` file that follows the structure defined in `./schema/`.
- [ ] Created version folders and added `manifest.jsonc` files for each version.
- [x] Followed the folder structure guidelines for manufacturer and sensor/device model.
- [ ] The code has unit test and it's in TypeScript.

## Additional Notes

Please add any other information that you think is important.

2024-06-28 17:21 UTC, Freddyminu approved these changes

2024-07-02 14:02 UTC, vitorfdl requested changes

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ems/v1.0.0/payload.js
> +  const serie = data.serie || new Date().getTime();
serie is deprecated. This payload parser must be updated to use group instead

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ers-co2/v1.0.0/payload.js
> +        serie: object_item[key].serie || serie,
serie is deprecated. This payload parser must be updated to use group instead

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ers-co2/v1.0.0/payload.js
> +  const serie = data.serie || new Date().getTime();
serie is deprecated. This payload parser must be updated to use group instead

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ers-desk/v1.0.0/payload.js
> +  const serie = data.serie || new Date().getTime();
serie is deprecated. This payload parser must be updated to use group instead

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ers-eye/v1.0.0/payload.js
> +  const serie = data.serie || new Date().getTime();
serie is deprecated. This payload parser must be updated to use group instead

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ers-lite/v1.0.0/payload.js
> +  const serie = data.serie || new Date().getTime();
serie is deprecated. This payload parser must be updated to use group instead

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ers-sound/v1.0.0/payload.js
> +  const serie = data.serie || new Date().getTime();
serie is deprecated. This payload parser must be updated to use group instead

2024-07-02 14:02 UTC, vitorfdl commented on decoders/connector/elsys/ers/v1.0.0/payload.js
> +  const serie = data.serie || new Date().getTime();
serie is deprecated. This payload parser must be updated to use group instead

2024-07-03 14:25 UTC, Freddyminu commented
@mateuscardosodeveloper  Add the following tests: 

describe("Shall not be parsed", () => {
  let payload = [
    { variable: "shallnotpass", value: "04096113950292" },
    { variable: "fport", value: 9 },
  ];
  
  payload = decoderRun(file_path, { payload });
  
  test("Output Result", () => {
    expect(Array.isArray(payload)).toBe(true);
  });

  test("Not parsed Result", () => {
    expect(payload).toEqual([
      { variable: "shallnotpass", value: "04096113950292" },
      { variable: "fport", value: 9 },
    ]);
  });
});

2024-07-03 18:06 UTC, vitorfdl approved these changes

2024-07-12 12:58 UTC, merged