1.add R718n125 support
tago-io/decoders pull request #40
Opened 2024-07-03 00:25 UTC by netvox-tech

1.add R718n125 support

2024-07-03 14:21 UTC, mateuscardosodeveloper requested changes

2024-07-03 14:21 UTC, mateuscardosodeveloper commented on decoders/connector/netvox/r718n125/v1.0.0/payload.ts
> +function Decoder_r718n125(input, port) {
Add type annotation for the function, example:
```ts
function Decoder_r718n125(input: Buffer, port: number) {
```

2024-07-03 14:21 UTC, mateuscardosodeveloper commented on decoders/connector/netvox/r718n125/v1.0.0/payload.ts
> +function decodePort6_r718n125(bytes) {
Add type annotation for the function.

2024-07-03 14:21 UTC, mateuscardosodeveloper commented on decoders/connector/netvox/r718n125/v1.0.0/payload.ts
> +function decodePort7_r718n125(bytes) {
Add type annotation for the function

2024-07-03 14:21 UTC, mateuscardosodeveloper commented on decoders/connector/netvox/r718n125/v1.0.0/payload.ts
> +    payload = payload.concat(data.map((x) => ({...x, serie: payload_r718n125.group, time: payload_r718n125.time})));
Field "serie" is deprecated, replace to "group":
```ts
payload = payload.concat(data.map((x) => ({ ...x, group: payload_r718n125.group, time: payload_r718n125.time })));
```

2024-07-03 14:21 UTC, mateuscardosodeveloper commented on decoders/connector/netvox/r718n125/v1.0.0/payload.ts
> +function Decoder_r718n125(input, port) {
Install the package `npm install -D @tago-io/sdk` and declare the variable payload.
```ts
import { DataToSend } from "@tago-io/sdk/lib/types";

declare let payload: DataToSend[];
```

Probably when you declare the payload variable you will get errors on line 82 and 83 replace it with:
```ts
    const buffer = Buffer.from(payload_r718n125?.value as string, "hex");
    const data = Decoder_r718n125(buffer, port_r718n125 as number);
```

2024-07-03 14:21 UTC, mateuscardosodeveloper commented on decoders/connector/netvox/r718n125/v1.0.0/payload.test.ts
> +function preparePayload(payloadHex, port) {
Add type annotation for the function.

2024-07-12 13:12 UTC, Freddyminu commented
Hi @netvox-tech ,

Thank you for creating this Pull Request! I have made some modifications and created a new PR, which has been merged. Therefore, this PR is no longer needed.

2024-07-12 13:12 UTC, closed without merging