Add Dragino WL03A-LB connector and its dependencies
tago-io/decoders pull request #69
Opened 2024-07-22 14:26 UTC by Freddyminu

## Decoder Description

Adding a water leak LoRaWAN sensor from dragino

## Type of change

- [X] Adding a new Decoder of Connector
- [ ] Adding a new Decoder of Network
- [ ] Update or fixing an issue in existing Decoder

## Decoder Information and Payload to test and review

- [X] Documentation of the hardware or protocol: http://wiki.dragino.com/xwiki/bin/view/Main/User%20Manual%20for%20LoRaWAN%20End%20Nodes/WL03A-LB_LoRaWAN_None-Position_Rope_Type_Water_Leak_Controller_User_Manual/
- [X] Payload of example the test the decoder:

## Checklist for Adding a New Decoder

- [X] Created a new folder under `./decoders/network/` or `./decoders/connector/` with the name of your decoder.
- [X] Added a `network.jsonc` or `connector.jsonc` file that follows the structure defined in `./schema/`.
- [X] Created version folders and added `manifest.jsonc` files for each version.
- [X] Followed the folder structure guidelines for manufacturer and sensor/device model.
- [X] The code has unit test and it's in TypeScript.

## Additional Notes

Please add any other information that you think is important.

2024-07-22 14:44 UTC, mateuscardosodeveloper requested changes

2024-07-22 14:44 UTC, mateuscardosodeveloper commented on decoders/connector/dragino/wl03alb/v1.0.0/payload.test.ts
> +// describe("Port 3 unit tests", () => {
Why leave this unit test commented? If it's not going to be used, it's better to remove

2024-07-22 14:44 UTC, mateuscardosodeveloper commented on decoders/connector/dragino/wl03alb/v1.0.0/payload.ts
> +/* eslint-disable default-case */
Type annotation needs to be added for the functions below

2024-07-22 15:05 UTC, FabianoEger approved these changes

2024-07-23 12:05 UTC, mateuscardosodeveloper approved these changes

2024-07-23 12:57 UTC, merged