adding atomsenses decoder
tago-io/decoders pull request #75
Opened 2024-07-31 07:25 UTC by mattAtomsenses

## Decoder Description

This is to add Atomsenses decoder.

## Type of change

- [ ] Adding a new Decoder of Connector

## Decoder Information and Payload to test and review

- [ ] Documentation of the hardware or protocol:
- [ ] Payload of example the test the decoder:

## Checklist for Adding a New Decoder

- [ ] Created a new folder under `./decoders/connector/` with the name atomsenses.
- [ ] Added a `network.jsonc` or `connector.jsonc` file that follows the structure defined in `./schema/`.
- [ ] Created version folders and added `manifest.jsonc` files for each version.
- [ ] Followed the folder structure guidelines for manufacturer and sensor/device model.
- [ ] The code has unit test and it's in TypeScript.

## Additional Notes

Added AS-201 & AS-204 for now.

2024-07-31 13:41 UTC, Freddyminu requested changes

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-201/description.md
The description.md file is the subtitle that will be shown here: 

<img width="587" alt="image" src="https://github.com/user-attachments/assets/fde5e08c-0f79-45d3-9c8e-97b4475c31c1">

This field is searchable. (When a user searches for a device on the platform, it uses these words)

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-201/description.md
Also, to ensure the description is clear and focuses on the specific capabilities and features of the device, we recommend avoiding subjective terms like "highly accurate" and "competitively priced." Instead, please state measurable facts or specifications.

For example:

Instead of saying "highly accurate," you could mention the specific accuracy level or tolerance.
Rather than "competitively priced," you might focus on the cost-saving aspects or comparison with industry standards.

This approach will help potential customers understand the exact value and functionality of the sensor

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-201/assets/logo.png
The background of the image must be transparent.

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-201/v1.0.0/payload.test.ts
You must add tests with payloads and expected outputs, heres and example from another connector: 

``` javascript
describe("Port 5 unit tests", () => {
  const payloadHex = "20010002010B45";
  const port = 5;
  const result = preparePayload(payloadHex, port);

  test("Port 5 variable values", () => {
    expect(result.sensor_model?.value).toBe("CPL03-LB");
    expect(result.firmware_version?.value).toBe("1.0.0");
    expect(result.frequency_band?.value).toBe("US915");
    expect(result.sub_band?.value).toBe(1);
    expect(result.bat?.value).toBe(2.885);
  });
});
```

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-201/v1.0.0/payload.ts
> +  const serie = new Date().getTime();
Please change "serie" to "group", it is depreciated.

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-204/assets/logo.png
The background of the image must be transparent.

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-204/description.md
There's a typo on "todetectammonia". Also, reminder that the subtitle does not contain a lot of space, try making a short sentence.

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-204/v1.0.0/payload.test.ts
You must add tests with payloads and expected outputs.

2024-07-31 13:41 UTC, Freddyminu commented on decoders/connector/atomsenses/as-204/v1.0.0/payload.ts
> +    const serie = new Date().getTime();
Please change "serie" to "group", it is depreciated.

2024-08-02 12:28 UTC, Freddyminu commented on decoders/connector/atomsenses/as-201/v1.0.0/payload-config.jsonc
> +  "install_text": "AS-201 is a compact indoor ambience monitoring sensor including humidity, temperature, CO2 for wireless LoRa network.\n\n**LoRaWan**\n* Frequency: CN470/ EU868/ US915/ AU915/ AS923
Please remove external link they aren't allowed as they may become broken in the future.

2024-08-02 12:28 UTC, Freddyminu commented on decoders/connector/atomsenses/as-204/v1.0.0/payload-config.jsonc
> +  "install_text": "AS-204 is a compact indoor ambience monitoring sensor for measurement of temperature, humidity, CO2 concentration, NH3, H2S. Sensor data is transmitted using LoRaWAN® technology.\n
Please remove external link they aren't allowed as they may become broken in the future.

2024-08-02 12:30 UTC, Freddyminu requested changes

2024-08-02 12:30 UTC, Freddyminu commented on decoders/connector/atomsenses/as-201/v1.0.0/payload-config.jsonc
> +  "install_text": "AS-201 is a compact indoor ambience monitoring sensor including humidity, temperature, CO2 for wireless LoRa network.\n\n**LoRaWan**\n* Frequency: CN470/ EU868/ US915/ AU915/ AS923
Please remove external link they aren't allowed as they may become broken in the future.

2024-08-02 13:26 UTC, Freddyminu approved these changes

2024-08-02 14:20 UTC, mateuscardosodeveloper approved these changes

2024-08-02 14:31 UTC, merged