Add/unify decentlab devices
tago-io/decoders pull request #76
Opened 2024-08-01 09:54 UTC by decentlab

## Decoder Description

Added all Decentlab device (connector) decoders from TTN repository.

## Type of change

- [x] Adding a new Decoder of Connector
- [x] Update or fixing an issue in existing Decoder

## Decoder Information and Payload to test and review

- [x] Documentation of the hardware or protocol: https://www.decentlab.com/support
- [x] Payload of example the test the decoder: https://github.com/decentlab/decentlab-decoders

## Checklist for Adding a New Decoder

- [x] Created a new folder under `./decoders/network/` or `./decoders/connector/` with the name of your decoder.
- [x] Added a `network.jsonc` or `connector.jsonc` file that follows the structure defined in `./schema/`.
- [x] Created version folders and added `manifest.jsonc` files for each version.
- [x] Followed the folder structure guidelines for manufacturer and sensor/device model.
- [x] The code has unit test and it's in TypeScript.

## Additional Notes

The existing decoders have been reverted back to the original TTN device repo version. This simplifies creating the decoders and makes sure that they uniformly work as expected over many platforms. Besides, the modifications made by TagoIO was mainly cosmetic, and there was no logic change.

We intentionally keep the decoders' syntax such that they're supported on most platforms with a minimal change.

2024-08-01 14:24 UTC, mateuscardosodeveloper requested changes
There are a few points that need to be corrected or improved:

1. The images should have a transparent background.
2. The `description.md` file serves as the subtitle displayed on the devices' screen.
   a. This field is searchable. (When a user searches for a device on the platform, they use these words).
   b. It is recommended that `description.md` be clear and focus on the specific capabilities and features of the device.
3. 3. The new decoders added must be made in TypeScript and also add type annotation. E.g:
```ts
function toTagoFormat(object_item: {}, group: number, prefix: string = "") {
  //...
}
```
  a. When changing the payload to TypeScript, don't forget to edit the `connector.jsonc` file to `payload.ts`.

When changing the payload to TypeScript, don't forget to edit the `connector.jsonc` file to `payload.ts`.
4. Each decoder must have unit tests. Here is an example of a unit test you can use.
```ts
import { describe, test, expect } from "vitest";

import { decoderRun } from "../../../../../src/functions/decoder-run";

const file_path = "decoders/connector/your-path/payload.js" as const;

describe("Shall not be parsed", () => {
  let payload = [{ variable: "shallnotpass", value: "04096113950292" }];
  payload = decoderRun(file_path, { payload });
  test("Output Result", () => {
    expect(Array.isArray(payload)).toBe(true);
  });

  test("Not parsed Result", () => {
    expect(payload).toEqual([{ variable: "shallnotpass", value: "04096113950292" }]);
  });
});
```

If you can add a unit test for the payload parser, that would be great.

2024-08-01 14:37 UTC, decentlab commented
Thanks for the review.

We followed the existing payload decoders that were added by TagoIO. It would have been more efficient if we knew the different requirements before creating these decoders. Would it be possible to add the decoders now as it is, and we improve them iteratively?

Some questions:

- 2a, 2b: Could you make an example improvement on one device please?
- 3a: Do you mean that we need to restructure all payloads to a real TypeScript? Or just type annotations on the functions?  Or change just the `toTagoFormat` signature?

2024-08-01 15:17 UTC, mateuscardosodeveloper commented
> Thanks for the review.
> 
> We followed the existing payload decoders that were added by TagoIO. It would have been more efficient if we knew the different requirements before creating these decoders. Would it be possible to add the decoders now as it is, and we improve them iteratively?
> 
> Some questions:
> 
> * 2a, 2b: Could you make an example improvement on one device please?
> * 3a: Do you mean that we need to restructure all payload decoders to a real TypeScript? Or just add type annotations in the function signatures? Or change just the `toTagoFormat` signature?

Since the payload was created by TagoIO, I see no issue in approving it as it currently stands. However, I kindly request that you add the unit test mentioned in topic 4.

Regarding points 2a and 2b: These are just informational, indicating that they pertain to the searchable fields within the platform for the sensor.
![searchable-devices](https://github.com/user-attachments/assets/ea097eb4-ada2-47e3-84b8-b56578331f78)

2024-08-02 15:19 UTC, decentlab commented
Thanks for considering to approve the decoders as they are now. We have added unit tests for the payload parsers.

2024-08-02 17:21 UTC, Freddyminu reviewed
Please remove the sensor name from all **description.md** files.

Additionally, ensure that the **install_text** contains only factual information about the device, avoiding any subjective phrases.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-alb/description.md
> +DL-ALB is an albedometer sensor over LoRaWAN®
Please remove the sensor name, example: "Albedometer sensor over LoRaWAN®"

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-dlr2-010/description.md
> +DL-DLR2-010 is a dual pulse counter dry contact transmitter over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-dlr2-012/description.md
> +DL-DLR2-012 is an analog strain gauge sensor transmitter over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-dlr2-011/description.md
> +DL-DLR2-011 is a dual digital input dry contact transmitter over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-ds18/description.md
> +DL-DS18 is a temperature sensor over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-dws/description.md
> +DL-DWS is a weighing scale over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-gmm/description.md
> +DL-GMM is a greenhouse multi monitor over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-iam/description.md
> +DL-IAM is an indoor ambiance monitor including co₂, tvoc and motion sensor over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-isf/description.md
> +DL-ISF is a sapflow sensor over LoRaWAN®
Please remove sensor name.

2024-08-02 17:21 UTC, Freddyminu commented on decoders/connector/decentlab/dl-itst/description.md
> +DL-ITST is an infrared thermometer/surface temperature sensor over LoRaWAN®
Please remove sensor name.

2024-08-02 17:56 UTC, decentlab commented
@Freddyminu, these have been done by TagoIO and we followed exactly how it was. Would it be possible if you approve this PR now, and we improve iteratively? Thanks.

2024-08-02 18:08 UTC, Freddyminu approved these changes

2024-08-02 18:10 UTC, mateuscardosodeveloper approved these changes

2024-08-05 17:51 UTC, merged