Add RA02G Decoder for Netvox Sensor over LoRaWAN
tago-io/decoders pull request #93
Opened 2024-11-01 18:23 UTC by nishchayjeet

## Decoder Description

Explain the functionality of your decoder or any other relevant information.

## Type of change

- [ ] Adding a new Decoder of Connector
- [ ] Adding a new Decoder of Network
- [ ] Update or fixing an issue in existing Decoder

## Decoder Information and Payload to test and review

- [ ] Documentation of the hardware or protocol:
- [ ] Payload of example the test the decoder:

## Checklist for Adding a New Decoder

- [ ] Created a new folder under `./decoders/network/` or `./decoders/connector/` with the name of your decoder.
- [ ] Added a `network.jsonc` or `connector.jsonc` file that follows the structure defined in `./schema/`.
- [ ] Created version folders and added `manifest.jsonc` files for each version.
- [ ] Followed the folder structure guidelines for manufacturer and sensor/device model.
- [ ] The code has unit test and it's in TypeScript.

## Additional Notes

Please add any other information that you think is important.

2024-11-01 18:26 UTC, nishchayjeet commented
This connector is currently working successfully on our CityKinect account, under the device name "Netvox RA02G." All features and parsing functionalities have been tested and validated. Please let us know if you need any further information.

2024-12-05 19:20 UTC, Freddyminu commented
Thank you @nishchayjeet I'll be reviewing this PR tomorrow and hopefully it will be approved! :)

2024-12-06 13:49 UTC, Freddyminu requested changes
Nice work on the first commit! The only thing left is the unit test. Thanks for your contribution!

2024-12-06 13:49 UTC, Freddyminu commented on decoders/connector/netvox/ra02g/description.md
> +# Wireless Cigarette Smoke, Vaping, and Bullying Alarm Sensor over LoRaWAN™
Please remove the #

2024-12-06 13:49 UTC, Freddyminu commented on decoders/connector/netvox/ra02g/v1.0.0/payload-config.jsonc
> +    "install_text": "\nRA02G is a smart indoor sensor designed for high-reliability wireless control and alarm detection. It detects smoke, noise, and tampering, providing versatile alarm functionali
Please remove or update the link, It's broken.

2024-12-06 13:49 UTC, Freddyminu commented on decoders/connector/netvox/ra02g/v1.0.0/payload-config.jsonc
> +      "../../../../network/lorawan-citykinect/v1.0.0/payload.js",
Just a reminder: Make sure you've added all the networks this connector can be used with.

2024-12-06 13:49 UTC, Freddyminu commented on decoders/connector/netvox/ra02g/v1.0.0/payload.js
> +
Please add unit tests in order to make sure the connector is working. Please use the Netvox R312a as an example.

2025-04-08 12:53 UTC, Freddyminu commented
@nishchayjeet Please let us know if you plan to address the issues mentioned above. If we don't see any activity on this PR by April 30th, we will need to remove it.

2025-04-08 12:53 UTC, closed without merging